url: https://www.levivoelz.com
highlighter: rouge
plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
collections:
  projects:
    output: true
    permalink: /:collection/:name
  stories:
    output: true
    permalink: /:collection/:name
  posts:
    output: true
    permalink: /:collection/:year/:month/:day/:title
defaults:
  -
    scope:
      path: "slides/*"
    values:
      sitemap: false
